name: Build and push docker image

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
    paths-ignore:
      - 'releases/**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
      packages: write
    secrets: inherit
    uses: ./.github/workflows/build_web.yaml
